// Code generated by go generate; DO NOT EDIT.
package schemas

import (
	"mime/multipart"
)

type TokenPayload struct {
	UserId string `json:"userId" bson:"userId" validate:"required,hexadecimal,len=24"`
	Email  string `json:"email" bson:"email" validate:"required,email"`
}

type SignupForm struct {
	Name     string                `json:"name" bson:"name" validate:"required,min=2"`
	Email    string                `json:"email" bson:"email" validate:"required,email"`
	Password any                   `json:"password" bson:"password" validate:"required,min=8"`
	Image    *multipart.FileHeader `json:"image" bson:"image"`
}

type SigninForm struct {
	Username string `json:"username" bson:"username" validate:"required,email"`
	Password any    `json:"password" bson:"password" validate:"required,min=8"`
}

type EncodedToken struct {
	AccessToken string `json:"access_token" bson:"access_token" validate:"required"`
	TokenType   string `json:"token_type" bson:"token_type" validate:"required,oneof=bearer"`
	UserId      string `json:"userId" bson:"userId" validate:"required,hexadecimal,len=24"`
	Email       string `json:"email" bson:"email" validate:"required,email"`
	ExpiresIn   int    `json:"expires_in" bson:"expires_in" validate:"required"`
}
