// Code generated by go generate; DO NOT EDIT.
package schemas

import (
	"backend/internal/types_"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"mime/multipart"
	"time"
)

type UserDB struct {
	Id        primitive.ObjectID `json:"id" validate:"hexadecimal,len=24" example:"683b21134e2e5d46978daf1f" bson:"_id,omitempty"`                 // The user ID, 24 characters
	Name      string             `json:"name" validate:"min=2" example:"Slim Beji" bson:"name"`                                                    // The user name, two characters at least
	Email     string             `json:"email" validate:"email" example:"mslimbeji@gmail.com" bson:"email"`                                        // The user email
	IsAdmin   bool               `json:"isAdmin" example:"false" bson:"isAdmin"`                                                                   // Whether the user is an admin or not
	Password  string             `json:"password" validate:"min=8" example:"very_secret" bson:"password"`                                          // The user password, 8 characters at least
	ImageUrl  string             `json:"imageUrl" validate:"omitempty" example:"avatar2_80e32f88-c9a5-4fcd-8a56-76b5889440cd.jpg" bson:"imageUrl"` // local url on the storage
	Places    []string           `json:"places" validate:"dive,hexadecimal,len=24" example:"683b21134e2e5d46978daf1f" bson:"places"`               // The id of places belonging to the user, 24 characters
	CreatedAt time.Time          `json:"createdAt" bson:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt" bson:"updatedAt"`
}

type UserSeed struct {
	Ref      int
	Name     string `json:"name" validate:"min=2" example:"Slim Beji" bson:"name"`                                                    // The user name, two characters at least
	Email    string `json:"email" validate:"email" example:"mslimbeji@gmail.com" bson:"email"`                                        // The user email
	IsAdmin  bool   `json:"isAdmin" example:"false" bson:"isAdmin"`                                                                   // Whether the user is an admin or not
	Password string `json:"password" validate:"min=8" example:"very_secret" bson:"password"`                                          // The user password, 8 characters at least
	ImageUrl string `json:"imageUrl" validate:"omitempty" example:"avatar2_80e32f88-c9a5-4fcd-8a56-76b5889440cd.jpg" bson:"imageUrl"` // local url on the storage
}

type UserCreate struct {
	Name     string `json:"name" validate:"min=2" example:"Slim Beji" bson:"name"`                                                    // The user name, two characters at least
	Email    string `json:"email" validate:"email" example:"mslimbeji@gmail.com" bson:"email"`                                        // The user email
	IsAdmin  bool   `json:"isAdmin" example:"false" bson:"isAdmin"`                                                                   // Whether the user is an admin or not
	Password string `json:"password" validate:"min=8" example:"very_secret" bson:"password"`                                          // The user password, 8 characters at least
	ImageUrl string `json:"imageUrl" validate:"omitempty" example:"avatar2_80e32f88-c9a5-4fcd-8a56-76b5889440cd.jpg" bson:"imageUrl"` // local url on the storage
}

type UserPost struct {
	Name     string                `json:"name" form:"name" validate:"min=2" example:"Slim Beji" bson:"name"`               // The user name, two characters at least
	Email    string                `json:"email" form:"email" validate:"email" example:"mslimbeji@gmail.com" bson:"email"`  // The user email
	IsAdmin  bool                  `json:"isAdmin" form:"isAdmin" example:"false" bson:"isAdmin"`                           // Whether the user is an admin or not
	Password string                `json:"password" form:"password" validate:"min=8" example:"very_secret" bson:"password"` // The user password, 8 characters at least
	Image    *multipart.FileHeader `json:"image" form:"image" validate:"omitempty" bson:"image" swaggerignore:"true"`       // User's profile image (JPEG)
}

type UserRead struct {
	Id       string   `json:"id" validate:"hexadecimal,len=24" example:"683b21134e2e5d46978daf1f" bson:"_id,omitempty"`                 // The user ID, 24 characters
	Name     string   `json:"name" validate:"min=2" example:"Slim Beji" bson:"name"`                                                    // The user name, two characters at least
	Email    string   `json:"email" validate:"email" example:"mslimbeji@gmail.com" bson:"email"`                                        // The user email
	IsAdmin  bool     `json:"isAdmin" example:"false" bson:"isAdmin"`                                                                   // Whether the user is an admin or not
	ImageUrl string   `json:"imageUrl" validate:"omitempty" example:"avatar2_80e32f88-c9a5-4fcd-8a56-76b5889440cd.jpg" bson:"imageUrl"` // local url on the storage
	Places   []string `json:"places" validate:"dive,hexadecimal,len=24" example:"683b21134e2e5d46978daf1f" bson:"places"`               // The id of places belonging to the user, 24 characters
}

type UsersPaginated = types_.RecordsPaginated[PlaceRead]

type UserFilters struct {
	Page   int      `json:"page" default:"1"`
	Size   int      `json:"size" default:"100"`
	Sort   []string `json:"sort" validate:"dive,oneof=createdAt -createdAt name -name email -email" example:"createdAt"`
	Fields []string `json:"fields" validate:"dive,oneof=id name email isAdmin imageUrl places" example:"id,name"`
	Id     []string `json:"id" form:"id" filter:"string,hexadecimal,len=24" example:"683b21134e2e5d46978daf1f" collectionFormat:"multi"` // The user ID, 24 characters
	Name   []string `json:"name" form:"name" filter:"string,min=2" example:"eq:Slim Beji" collectionFormat:"multi"`                      // The user name, two characters at least
	Email  []string `json:"email" form:"email" filter:"string,email" example:"eq:mslimbeji@gmail.com" collectionFormat:"multi"`          // The user email
}

type UserUpdate struct {
	Name     *string `json:"name" validate:"omitempty,min=2" example:"Slim Beji" bson:"name"`             // The user name, two characters at least
	Email    *string `json:"email" validate:"omitempty,email" example:"mslimbeji@gmail.com" bson:"email"` // The user email
	Password *string `json:"password" validate:"omitempty,min=8" example:"very_secret" bson:"password"`   // The user password, 8 characters at least
}

type UserPut = UserUpdate
