import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1770569167183 implements MigrationInterface {
    name = "Init1770569167183";

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Db setup
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "vector";`);

        // Autogenerated
        await queryRunner.query(
            `CREATE TABLE "places" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "address" character varying NOT NULL, "imageUrl" character varying, "location" jsonb NOT NULL, "embedding" vector(384), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "creatorId" integer, CONSTRAINT "PK_1afab86e226b4c3bc9a74465c12" PRIMARY KEY ("id"))`
        );
        await queryRunner.query(
            `CREATE INDEX "IDX_7137f4570006091685591ec767" ON "places" ("createdAt") `
        );
        await queryRunner.query(
            `CREATE INDEX "idx_place_creator" ON "places" ("creatorId") `
        );
        await queryRunner.query(
            `CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "imageUrl" character varying, "isAdmin" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`
        );
        await queryRunner.query(
            `CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `
        );
        await queryRunner.query(
            `CREATE INDEX "IDX_204e9b624861ff4a5b26819210" ON "users" ("createdAt") `
        );
        await queryRunner.query(
            `ALTER TABLE "places" ADD CONSTRAINT "FK_3be8f124c37385b25a898a45ed2" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`
        );

        // Constraints of the embedding vector and the locan jsonb schema
        await queryRunner.query(
            `CREATE INDEX idx_place_embedding_vector ON places USING ivfflat (embedding vector_cosine_ops)`
        );
        await queryRunner.query(
            `ALTER TABLE "places"
            ADD CONSTRAINT location_structure CHECK (
                location IS NULL OR (
                    location ? 'lat' AND
                    location ? 'lng' AND
                    jsonb_typeof(location->'lat') = 'number' AND
                    jsonb_typeof(location->'lng') = 'number'
                )
            );`
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Dropping cutom constraints
        await queryRunner.query(
            `DROP INDEX IF EXISTS "public"."idx_place_embedding_vector"`
        );
        await queryRunner.query(
            `ALTER TABLE "places" DROP CONSTRAINT IF EXISTS "embedding_length"`
        );
        await queryRunner.query(
            `ALTER TABLE "places" DROP CONSTRAINT IF EXISTS "location_structure"`
        );

        // Auto-generated
        await queryRunner.query(
            `ALTER TABLE "places" DROP CONSTRAINT "FK_3be8f124c37385b25a898a45ed2"`
        );
        await queryRunner.query(
            `DROP INDEX "public"."IDX_204e9b624861ff4a5b26819210"`
        );
        await queryRunner.query(
            `DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`
        );
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_place_creator"`);
        await queryRunner.query(
            `DROP INDEX "public"."IDX_7137f4570006091685591ec767"`
        );
        await queryRunner.query(`DROP TABLE "places"`);
    }
}
