import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1770723637893 implements MigrationInterface {
    name = "Init1770723637893";

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Db setup
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "vector";`);

        // Autogenerated
        await queryRunner.query(
            `CREATE TABLE "places" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "address" character varying NOT NULL, "image_url" character varying, "location" jsonb NOT NULL, "embedding" vector(384), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "creator_id" integer NOT NULL, CONSTRAINT "PK_1afab86e226b4c3bc9a74465c12" PRIMARY KEY ("id"))`
        );
        await queryRunner.query(
            `CREATE INDEX "IDX_d7044aed30c5dde6427ef3f52d" ON "places" ("created_at") `
        );
        await queryRunner.query(
            `CREATE INDEX "idx_place_creator" ON "places" ("creator_id") `
        );
        await queryRunner.query(
            `CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "image_url" character varying, "is_admin" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`
        );
        await queryRunner.query(
            `CREATE INDEX "IDX_c9b5b525a96ddc2c5647d7f7fa" ON "users" ("created_at") `
        );
        await queryRunner.query(
            `ALTER TABLE "places" ADD CONSTRAINT "FK_b3042c1fdd710dc42964416569d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`
        );

        // Constraints of the embedding vector and the location jsonb schema
        await queryRunner.query(
            `CREATE INDEX idx_place_embedding_vector ON places USING ivfflat (embedding vector_cosine_ops)`
        );
        await queryRunner.query(
            `ALTER TABLE "places"
            ADD CONSTRAINT location_structure CHECK (
                location ? 'lat' AND
                location ? 'lng' AND
                jsonb_typeof(location->'lat') = 'number' AND
                jsonb_typeof(location->'lng') = 'number'
            );`
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Dropping cutom constraints
        await queryRunner.query(
            `DROP INDEX IF EXISTS "public"."idx_place_embedding_vector"`
        );
        await queryRunner.query(
            `ALTER TABLE "places" DROP CONSTRAINT IF EXISTS "location_structure"`
        );

        // Autogenerated
        await queryRunner.query(
            `ALTER TABLE "places" DROP CONSTRAINT "FK_b3042c1fdd710dc42964416569d"`
        );
        await queryRunner.query(
            `DROP INDEX "public"."IDX_c9b5b525a96ddc2c5647d7f7fa"`
        );
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_place_creator"`);
        await queryRunner.query(
            `DROP INDEX "public"."IDX_d7044aed30c5dde6427ef3f52d"`
        );
        await queryRunner.query(`DROP TABLE "places"`);
    }
}
