// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/signin": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User authentication",
                "parameters": [
                    {
                        "minLength": 8,
                        "type": "string",
                        "example": "very_secret",
                        "description": "The user password, 8 characters at least",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "mslimbeji@gmail.com",
                        "description": "The user email (We use username here because of OAuth spec)",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.EncodedToken"
                        }
                    }
                }
            }
        },
        "/api/auth/signup": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "type": "string",
                        "example": "mslimbeji@gmail.com",
                        "description": "The user email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minLength": 2,
                        "type": "string",
                        "example": "Slim Beji",
                        "description": "The user name, two characters at least",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minLength": 8,
                        "type": "string",
                        "example": "very_secret",
                        "description": "The user password, 8 characters at least",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "User's profile image (JPEG)",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.EncodedToken"
                        }
                    }
                }
            }
        },
        "/api/hello-world/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hello World"
                ],
                "summary": "Hello World Endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.HelloResponse"
                        }
                    }
                }
            }
        },
        "/api/hello-world/admin": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hello World"
                ],
                "summary": "Hello World Endpoint for admins only",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.HelloAdminResponse"
                        }
                    }
                }
            }
        },
        "/api/hello-world/user": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hello World"
                ],
                "summary": "Hello World Endpoint for authenticated users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.HelloUserResponse"
                        }
                    }
                }
            }
        },
        "/api/places/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Place"
                ],
                "summary": "Search and Filter places",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "ilike:boulevard"
                        ],
                        "description": "The place address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "gt:2025-09-28"
                        ],
                        "description": "creation datetime",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "in:123456789"
                        ],
                        "description": "The ID of the place creator",
                        "name": "creator_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "like:football"
                        ],
                        "description": "The place description, 10 characters minimum",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "id",
                                "title",
                                "description",
                                "address",
                                "location",
                                "image_url",
                                "creator_id",
                                "created_at"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "id",
                            "location"
                        ],
                        "description": "Fields to include in the response; omit for complete data",
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "123456789"
                        ],
                        "description": "The ID of the place",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "gt:3.5"
                        ],
                        "description": "The latitude of the place",
                        "name": "location_lat",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "lt:4.5"
                        ],
                        "description": "The longitude of the place",
                        "name": "location_lng",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "The page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 100,
                        "description": "Items per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "created_at",
                                "-created_at",
                                "title",
                                "-title",
                                "description",
                                "-description",
                                "address",
                                "-address"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "-created_at"
                        ],
                        "description": "Fields to use for sorting. Use the '-' for descending sorting",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "eq:Some Place"
                        ],
                        "description": "The place title/name, 10 characters minimum",
                        "name": "title",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.PlacesPaginated"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Place"
                ],
                "summary": "Place creation",
                "parameters": [
                    {
                        "minLength": 1,
                        "type": "string",
                        "example": "Fulham road",
                        "description": "The place address",
                        "name": "address",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 123456789,
                        "description": "The ID of the place creator",
                        "name": "creator_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minLength": 10,
                        "type": "string",
                        "example": "Stadium of Chelsea football club",
                        "description": "The place description, 10 characters minimum",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": 51.48180425016331,
                        "description": "The latitude of the place",
                        "name": "lat",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": -0.19090418688755467,
                        "description": "The longitude of the place",
                        "name": "lng",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minLength": 10,
                        "type": "string",
                        "example": "Stamford Bridge",
                        "description": "The place title/name, 10 characters minimum",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Place Image (JPEG)",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.PlaceRead"
                        }
                    }
                }
            }
        },
        "/api/places/search": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Place"
                ],
                "summary": "Search and Retrieve places",
                "parameters": [
                    {
                        "description": "POST parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.PlaceSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.PlacesPaginated"
                        }
                    }
                }
            }
        },
        "/api/places/{placeId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Place"
                ],
                "summary": "Search and Retrieve place by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Place ID",
                        "name": "placeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "id",
                                "title",
                                "description",
                                "address",
                                "location",
                                "image_url",
                                "creator_id",
                                "created_at"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "id",
                            "title"
                        ],
                        "description": "Fields to include in the response; omit for complete data",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.PlaceRead"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Place"
                ],
                "summary": "Update places",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Place ID",
                        "name": "placeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PUT parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.PlacePut"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.PlaceRead"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Place"
                ],
                "summary": "Delete place by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Place ID",
                        "name": "placeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.PlaceDeleteResponse"
                        }
                    }
                }
            }
        },
        "/api/users/": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Search and Filter users",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "gt:2025-09-28"
                        ],
                        "description": "creation datetime",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "eq:mslimbeji@gmail.com"
                        ],
                        "description": "The user email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "id",
                                "name",
                                "email",
                                "is_admin",
                                "image_url",
                                "places",
                                "created_at"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "id",
                            "places"
                        ],
                        "description": "Fields to include in the response; omit for complete data",
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "123456789"
                        ],
                        "description": "The user ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": [
                            "eq:Slim Beji"
                        ],
                        "description": "The user name, two characters at least",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "The page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 100,
                        "description": "Items per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "created_at",
                                "-created_at",
                                "name",
                                "-name",
                                "email",
                                "-email"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "-created_at"
                        ],
                        "description": "Fields to use for sorting. Use the '-' for descending sorting",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.UsersPaginated"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User creation",
                "parameters": [
                    {
                        "type": "string",
                        "example": "mslimbeji@gmail.com",
                        "description": "The user email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "example": false,
                        "description": "Whether the user is an admin or not",
                        "name": "is_admin",
                        "in": "formData"
                    },
                    {
                        "minLength": 2,
                        "type": "string",
                        "example": "Slim Beji",
                        "description": "The user name, two characters at least",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minLength": 8,
                        "type": "string",
                        "example": "very_secret",
                        "description": "The user password, 8 characters at least",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "the user profile image",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.UserRead"
                        }
                    }
                }
            }
        },
        "/api/users/search": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Search and Retrieve users",
                "parameters": [
                    {
                        "description": "POST parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UserSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.UsersPaginated"
                        }
                    }
                }
            }
        },
        "/api/users/{userId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Search and Retrieve user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "id",
                                "name",
                                "email",
                                "is_admin",
                                "image_url",
                                "places",
                                "created_at"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "id",
                            "name"
                        ],
                        "description": "Fields to include in the response; omit for complete data",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.UserRead"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PUT parameters",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UserPut"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.UserRead"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Password": [
                            "admin"
                        ]
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UserDeleteResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "routes.HelloAdminResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello Admin Slim"
                }
            }
        },
        "routes.HelloResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello World!"
                }
            }
        },
        "routes.HelloUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello Slim"
                }
            }
        },
        "routes.PlaceDeleteResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Deleted place 507f1f77bcf86cd799439011"
                }
            }
        },
        "routes.UserDeleteResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Deleted user 507f1f77bcf86cd799439011"
                }
            }
        },
        "schemas.EncodedToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "A generated web token. The 'Bearer ' prefix needs to be added for authentication",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODIyNDVhOWY2YTU5ZjVlNjM2Y2NmYjEiLCJlbWFpbCI6ImJlamkuc2xpbUB5YWhvby5mciIsImlhdCI6MTc0NzMzNjUxMCwiZXhwIjoxNzQ3MzQwMTEwfQ.C4DCJKvGWhpHClpqmxHyxKLPYDOZDUlr-LA_2IflTXM"
                },
                "email": {
                    "description": "The user email",
                    "type": "string",
                    "example": "mslimbeji@gmail.com"
                },
                "expires_in": {
                    "description": "The UNIX timestamp the token expires at",
                    "type": "integer",
                    "example": 1751879562
                },
                "token_type": {
                    "description": "The type of token. Only 'bearer' is supported.",
                    "type": "string",
                    "enum": [
                        "bearer"
                    ],
                    "example": "bearer"
                },
                "user_id": {
                    "description": "The user ID, 24 characters",
                    "type": "integer",
                    "example": 123456789
                }
            }
        },
        "schemas.FlexLocation": {
            "type": "object",
            "properties": {
                "lat": {
                    "description": "The latitude of the place",
                    "type": "number",
                    "example": 51.48180425016331
                },
                "lng": {
                    "description": "The longitude of the place",
                    "type": "number",
                    "example": -0.19090418688755467
                }
            }
        },
        "schemas.Location": {
            "type": "object",
            "properties": {
                "lat": {
                    "description": "The latitude of the place",
                    "type": "number",
                    "example": 51.48180425016331
                },
                "lng": {
                    "description": "The longitude of the place",
                    "type": "number",
                    "example": -0.19090418688755467
                }
            }
        },
        "schemas.PlacePut": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "The place address",
                    "type": "string",
                    "minLength": 1,
                    "example": "Fulham road"
                },
                "description": {
                    "description": "The place description, 10 characters minimum",
                    "type": "string",
                    "minLength": 10,
                    "example": "Stadium of Chelsea football club"
                },
                "location": {
                    "description": "Location object (can be sent as JSON string)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schemas.FlexLocation"
                        }
                    ]
                },
                "title": {
                    "description": "The place title/name, 10 characters minimum",
                    "type": "string",
                    "minLength": 10,
                    "example": "Stamford Bridge"
                }
            }
        },
        "schemas.PlaceRead": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "The place address",
                    "type": "string",
                    "minLength": 1,
                    "example": "Fulham road"
                },
                "created_at": {
                    "description": "creation datetime                                            // last update datetime",
                    "type": "string",
                    "example": "2024-01-12T10:15:30.000Z"
                },
                "creator_id": {
                    "description": "The ID of the place creator",
                    "type": "integer",
                    "example": 123456789
                },
                "description": {
                    "description": "The place description, 10 characters minimum",
                    "type": "string",
                    "minLength": 10,
                    "example": "Stadium of Chelsea football club"
                },
                "id": {
                    "description": "The ID of the place",
                    "type": "integer",
                    "example": 123456789
                },
                "image_url": {
                    "description": "image url",
                    "type": "string",
                    "example": "avatar2_80e32f88-c9a5-4fcd-8a56-76b5889440cd.jpg"
                },
                "location": {
                    "description": "Location object (can be sent as JSON string)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schemas.Location"
                        }
                    ]
                },
                "title": {
                    "description": "The place title/name, 10 characters minimum",
                    "type": "string",
                    "minLength": 10,
                    "example": "Stamford Bridge"
                }
            }
        },
        "schemas.PlaceSearch": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "The place address",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ilike:boulevard"
                    ]
                },
                "created_at": {
                    "description": "creation datetime",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "gt:2025-09-28"
                    ]
                },
                "creator_id": {
                    "description": "The ID of the place creator",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "in:123456789"
                    ]
                },
                "description": {
                    "description": "The place description, 10 characters minimum",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "like:football"
                    ]
                },
                "fields": {
                    "description": "Fields to include in the response; omit for complete data",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "id",
                            "title",
                            "description",
                            "address",
                            "location",
                            "image_url",
                            "creator_id",
                            "created_at"
                        ]
                    },
                    "example": [
                        "id",
                        "location"
                    ]
                },
                "id": {
                    "description": "The ID of the place",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "123456789"
                    ]
                },
                "location_lat": {
                    "description": "The latitude of the place",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "gt:3.5"
                    ]
                },
                "location_lng": {
                    "description": "The longitude of the place",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "lt:4.5"
                    ]
                },
                "page": {
                    "description": "The page number",
                    "type": "integer",
                    "default": 1,
                    "minimum": 1
                },
                "size": {
                    "description": "Items per page",
                    "type": "integer",
                    "default": 100,
                    "maximum": 100,
                    "minimum": 1
                },
                "sort": {
                    "description": "Fields to use for sorting. Use the '-' for descending sorting",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "created_at",
                            "-created_at",
                            "title",
                            "-title",
                            "description",
                            "-description",
                            "address",
                            "-address"
                        ]
                    },
                    "example": [
                        "-created_at"
                    ]
                },
                "title": {
                    "description": "The place title/name, 10 characters minimum",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "eq:Some Place"
                    ]
                }
            }
        },
        "schemas.PlacesPaginated": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.PlaceRead"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "totalCount": {
                    "type": "integer",
                    "example": 40
                },
                "totalPages": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "schemas.UserPlace": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "The place address",
                    "type": "string",
                    "minLength": 1,
                    "example": "Fulham road"
                },
                "id": {
                    "description": "The ID of the place",
                    "type": "integer",
                    "example": 123456789
                },
                "title": {
                    "description": "The place title/name, 10 characters minimum",
                    "type": "string",
                    "minLength": 10,
                    "example": "Stamford Bridge"
                }
            }
        },
        "schemas.UserPut": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "The user email",
                    "type": "string",
                    "example": "mslimbeji@gmail.com"
                },
                "name": {
                    "description": "The user name, two characters at least",
                    "type": "string",
                    "minLength": 2,
                    "example": "Slim Beji"
                },
                "password": {
                    "description": "The user password, 8 characters at least",
                    "type": "string",
                    "minLength": 8,
                    "example": "very_secret"
                }
            }
        },
        "schemas.UserRead": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "creation datetime                                            // last update datetime",
                    "type": "string",
                    "example": "2024-01-12T10:15:30.000Z"
                },
                "email": {
                    "description": "The user email",
                    "type": "string",
                    "example": "mslimbeji@gmail.com"
                },
                "id": {
                    "description": "The user ID",
                    "type": "integer",
                    "example": 12345678
                },
                "image_url": {
                    "description": "image url",
                    "type": "string",
                    "example": "avatar2_80e32f88-c9a5-4fcd-8a56-76b5889440cd.jpg"
                },
                "is_admin": {
                    "description": "Whether the user is an admin or not",
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "description": "The user name, two characters at least",
                    "type": "string",
                    "minLength": 2,
                    "example": "Slim Beji"
                },
                "places": {
                    "description": "Places created by the user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.UserPlace"
                    }
                }
            }
        },
        "schemas.UserSearch": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "creation datetime",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "gt:2025-09-28"
                    ]
                },
                "email": {
                    "description": "The user email",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "eq:mslimbeji@gmail.com"
                    ]
                },
                "fields": {
                    "description": "Fields to include in the response; omit for complete data",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "id",
                            "name",
                            "email",
                            "is_admin",
                            "image_url",
                            "places",
                            "created_at"
                        ]
                    },
                    "example": [
                        "id",
                        "places"
                    ]
                },
                "id": {
                    "description": "The user ID",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "123456789"
                    ]
                },
                "name": {
                    "description": "The user name, two characters at least",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "eq:Slim Beji"
                    ]
                },
                "page": {
                    "description": "The page number",
                    "type": "integer",
                    "default": 1,
                    "minimum": 1
                },
                "size": {
                    "description": "Items per page",
                    "type": "integer",
                    "default": 100,
                    "maximum": 100,
                    "minimum": 1
                },
                "sort": {
                    "description": "Fields to use for sorting. Use the '-' for descending sorting",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "created_at",
                            "-created_at",
                            "name",
                            "-name",
                            "email",
                            "-email"
                        ]
                    },
                    "example": [
                        "-created_at"
                    ]
                }
            }
        },
        "schemas.UsersPaginated": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.PlaceRead"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "totalCount": {
                    "type": "integer",
                    "example": 40
                },
                "totalPages": {
                    "type": "integer",
                    "example": 2
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "/api/auth/signin"
        }
    },
    "tags": [
        {
            "description": "Registration and Authentication endpoints",
            "name": "Auth"
        },
        {
            "description": "Hello World endpoints",
            "name": "Hello World"
        },
        {
            "description": "User crud endpoints",
            "name": "User"
        },
        {
            "description": "Place crud endpoints",
            "name": "Place"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
