definitions:
  routes.ResponseExample:
    properties:
      message:
        type: string
    type: object
  schemas.EncodedToken:
    properties:
      access_token:
        description: A generated web token. The 'Bearer ' prefix needs to be added
          for authentication
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODIyNDVhOWY2YTU5ZjVlNjM2Y2NmYjEiLCJlbWFpbCI6ImJlamkuc2xpbUB5YWhvby5mciIsImlhdCI6MTc0NzMzNjUxMCwiZXhwIjoxNzQ3MzQwMTEwfQ.C4DCJKvGWhpHClpqmxHyxKLPYDOZDUlr-LA_2IflTXM
        type: string
      email:
        description: The user email
        example: mslimbeji@gmail.com
        type: string
      expires_in:
        description: The UNIX timestamp the token expires at
        example: 1751879562
        type: integer
      token_type:
        description: The type of token. Only 'bearer' is supported.
        enum:
        - bearer
        example: bearer
        type: string
      userId:
        description: The user ID, 24 characters
        example: 683b21134e2e5d46978daf1f
        type: string
    required:
    - access_token
    - email
    - expires_in
    - token_type
    - userId
    type: object
info:
  contact: {}
paths:
  /api/auth/signin:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - default: very_secret
        description: The user password, 8 characters at least
        in: formData
        minLength: 8
        name: password
        required: true
        type: string
      - default: mslimbeji@gmail.com
        description: The user email (We use username here because of OAuth spec)
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.EncodedToken'
      summary: User authentication
      tags:
      - Auth
  /api/auth/signup:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: The user email
        example: mslimbeji@gmail.com
        in: formData
        name: email
        required: true
        type: string
      - description: The user name, two characters at least
        example: Slim Beji
        in: formData
        minLength: 2
        name: name
        required: true
        type: string
      - description: The user password, 8 characters at least
        example: very_secret
        in: formData
        minLength: 8
        name: password
        required: true
        type: string
      - description: User's profile image (JPEG)
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.EncodedToken'
      summary: User registration
      tags:
      - Auth
  /api/hello-world/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.ResponseExample'
      summary: Hello World Endpoint
      tags:
      - Hello World
  /api/hello-world/admin:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.ResponseExample'
      security:
      - OAuth2Password:
        - admin
      summary: Hello World Endpoint for admins only
      tags:
      - Hello World
  /api/hello-world/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.ResponseExample'
      security:
      - OAuth2Password:
        - admin
      summary: Hello World Endpoint for authenticated users
      tags:
      - Hello World
securityDefinitions:
  OAuth2Password:
    flow: password
    tokenUrl: /api/auth/signin
    type: oauth2
swagger: "2.0"
tags:
- description: Registration and Authentication endpoints
  name: Auth
- description: Hello World endpoints
  name: Hello World
- description: User crud endpoints
  name: User
- description: Place crud endpoints
  name: Place
