"""init

Revision ID: e9df514e324d
Revises:
Create Date: 2026-02-18 18:56:26.815304

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9df514e324d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Db setup ### manually set
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_users_created_at"), "users", ["created_at"], unique=False
    )
    op.create_table(
        "places",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column(
            "location", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),  # type: ignore
            nullable=True,
        ),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_place_creator", "places", ["creator_id"], unique=False)
    op.create_index(
        op.f("ix_places_created_at"), "places", ["created_at"], unique=False
    )
    # ### end Alembic commands ###

    # Adding indexes and constraints ### manually set
    op.execute(
        "CREATE INDEX idx_place_embedding_vector ON places "
        "USING ivfflat (embedding vector_cosine_ops)"
    )
    op.execute("""
        ALTER TABLE places
        ADD CONSTRAINT location_structure CHECK (
            location ? 'lat' AND
            location ? 'lng' AND
            jsonb_typeof(location->'lat') = 'number' AND
            jsonb_typeof(location->'lng') = 'number'
        )
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # Dropping cutom constraints ### manually set
    op.execute("DROP INDEX IF EXISTS idx_place_embedding_vector")
    op.execute(
        "ALTER TABLE places DROP CONSTRAINT IF EXISTS location_structure"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_places_created_at"), table_name="places")
    op.drop_index("idx_place_creator", table_name="places")
    op.drop_table("places")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
